---
# The most valuable linters; they are required to pass for PR to be merged.

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # use "github.com/golang/protobuf/proto" instead
      - github.com/gogo/protobuf/proto
      # use "github.com/percona-platform/saas" instead
      - github.com/percona-platform/platform

  goimports:
    local-prefixes: github.com/percona/pmm-managed

linters:
  disable-all: true
  enable:
    - depguard
    - goimports
    - ineffassign
    - govet
    - staticcheck

issues:
  exclude-use-default: false
