dist: bionic
language: go

services:
  - docker

go:
  - 1.15.x
  - 1.16.x
  # TODO enable when 1.15.x is removed
  # - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

go_import_path: github.com/percona/pmm-admin

# skip non-trunk PMM-XXXX/SAAS-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{3,5}/
    - /^SAAS\-\d{2,5}/

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

env:
  global:
    - CODECOV_ENV=PMM_SERVER_IMAGE
    # REVIEWDOG_GITHUB_API_TOKEN
    - secure: "NdcqvN3wm/iOARMWCn6a6a1VF0yQGpD25ULMc7PJlpsGwujAzYQ7debbPX43INvShQIfGAVFmIrWmnfaWm+so80D8i9K3EIipeBMmrEnhd92+0bWbTh1bk/vxqvJBz7fVIjCEWppKPE+xHvebjGLRb4n27pdeuLvlc2uyjybd6mU54FBNwu44roiuMzHMd3Hu2+PIvf3mTC0JuWBFmKruzJqIlYKlnOyev/HQ8c3Nj9ehG3CmoGDxPcR7TPasI9MdlxYH89aRX8JK+GenYiSTFkkKDL3MbZ/R4e5p22vA5KMqntV2itHqoZLJ3yMtburpLwDN19mlw1dLnX/ZKQQLoDt1q8eOb1Jyr5TUQEfo0pHJEYqDl0dtmH3xlF12Zcbse7i95p1ZPKn+sSV5kJbzetfR0p4N84kD1KGqCNFdShv9nnZ8VJMIv7IUzazUAPcTIEH7A9tNXPc5Ux1QvnE/48yTa6iTUanOyPQiremxnEtueWe/c6cMGibAGTMF50T6Fn+JPV5vvTY1nTXQSlyhb3yX7x62xer5KZcbThFdyHxG8hwwRwbSQgRsZWJEE5/iUAvsDRqk5ZoVMDEshX12M9UmEL/WQIORkcalfY2f0K+7+tZeld+KnWcYvZMiweCDM47iwExeaybCkx/ShGes3LEKgpOoN01o/+GfHZqfpY="

  matrix:
    - PMM_SERVER_IMAGE=percona/pmm-server:2.0.0
    - PMM_SERVER_IMAGE=percona/pmm-server:2
    - PMM_SERVER_IMAGE=perconalab/pmm-server:dev-latest

before_install:
  - docker-compose up -d

install:
  # ensure that vendor/ is in sync with code and Gopkg.toml/lock
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep check
  # install reviewdog and golangci-lin
  - curl https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s

before_script:
  # ensure that files are not changed
  - make init
  - make format
  - git status
  - git diff --exit-code

script:
  # static analyze
  - make ci-reviewdog
  # for main_test.go
  - make install

  - make test-cover
  - make test-crosscover
  - make test-race

  - make check

after_success:
  - curl https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f cover.out -F cover -X fix
  - ./codecov -f crosscover.out -F crosscover -X fix

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: lmlesUUiOPssxPgNS7/CsUwd7XbKWbzbFskH4TXvFRGHoN0ZMGAtZK3VlXNT25sqek/NZZjADM7+lq9Jsm6HI+A6twsIzS4gp7Xqz3uToxwIukXNccQddMqMXgQF9qJWsN4RtTNs8zhOYoZNvPeOhseBURY5UIdJPD95iBocCnvToXaip4o/Kr/mrIFqRRXXb2oq6k93xzggFwwvnp78gS0gvYAWIvQYVjs4gUNuPWZvxFrWLuEPAPHwA6uLFdcqqv6RJPnWH5J6N5LTsIxJKktRCtXeJHBIdIIAq4gJJ8lYIQENjKw50h704adz73coXZDvyTnGVihUrCX2wIb896y/LEM8aCOTSJGnrPFS2pv/ZDluCdztfxbM6BWJsatTbuaXkZXy/5teVpt3VZgLwmcqVyFdGnCL00F8v6RNv7IhUbyTgmr13mNeeKGDzvVda1DKOx3PZ6L4b8Da9KLz+StoUZ7DWm1ZY8cUU2pAm7cYoJ7WSP8qLsgmbMaYpUS3wq4okxLcZbdTRef1ltcinKMwdjwLQOZtvohl/qpPZsiA2nc5pVkHr1pDMghBsUv31H5T7zsDLKYq1iL+MxTl/CWDxa/DbU7LmTO598NjVT654EH6R83ROFGmVXb3HGbD9u71tQs0Tq/Q2tsRXa0UsFvQKpyc1sIO1a5+0KyNx6Y=
