language: go

go:
  - 1.11.x
  - master

matrix:
  allow_failures:
    - go: master

script:
  # ensure that vendor/ is in sync with code and Gopkg.toml/lock
  - curl https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -L -o ~/dep && chmod +x ~/dep
  - ~/dep check

  - make check-license
  - make install
