dist: bionic
language: go
os: linux

services:
  - docker

go:
  - 1.16.x
  - tip

jobs:
  fast_finish: true
  allow_failures:
    - go: tip

go_import_path: github.com/percona/pmm-admin

# skip non-trunk PMM-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{4}/

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

env:
  global:
    - CODECOV_ENV=PMM_SERVER_IMAGE
    # REVIEWDOG_GITHUB_API_TOKEN
    - secure: "fESrhZcmZVyTLl1iyrhBAMni7kN3v+VDNIC/nZ6jYcSbhWrvH7wk55Pnv+7mnl9XW4wAkdT9M20H7DPPKImbSvIW6nhg5Lm+6otv5e3yRc8QK/JtX8eSapICiQ+bdtvgGP16xBNbyhfbhd3uo3yiuMdEYmKNR/cXIDMYgTHnx+7Vb1IvKB/Lk+2xCCiJaKOA/P+KtXmu29KUlAVwuT78J8QLbrsssWCGt4i4eD8xo44xZ1Z1tLQwH3c6SgCXYrI1fx/vVlXkdlBOX4JJOpyVHy2tu1MRCn6ViQHtqFgR/YxYNH98oOnrsoDafzOa03+Bn/Ti/gVyQkZ7N4VbWYmvqs5ijnTyIt1Tm/Obsivu8H+HRxd97RY1gsumVtJ6y28fWDWbYCAAWGmXT17hb56CdQ8mfDz3U80kCAbQvdPyzqKfoUji919kv5R/yWZYBKbIf2TDWEjwu5Ej4Alue0SrxSKMOkkOvsX5FXf18iQNsdFFMP0du7c15SU+1NzmmytehH7PvXtFnpa+s2UMnA2TEMArUilXG0EmHBG/nncy1T8EjlYMqpXz85tZCgKl/YyRvwvoxPGwcxwYTn+nSxJryuaPGED1zKx8EVeXplO654CubwK04SuoThDbT78W6IJYYhZM6sIBFeH8sxlF3pjc47k2v2fa90Fe+sw4XfBZF48="
  matrix:
    - PMM_SERVER_IMAGE=percona/pmm-server:2.0.0
    - PMM_SERVER_IMAGE=percona/pmm-server:2
    - PMM_SERVER_IMAGE=perconalab/pmm-server:dev-latest

before_install:
  - docker-compose up -d

install: skip
before_script:
  # ensure that files are not changed
  - make init
  - make format
  - git status
  - git diff --exit-code

script:
  # static analyze
  - make ci-reviewdog
  # for main_test.go
  - make install

  - make test-cover
  - make test-crosscover
  - make test-race

  - make check

after_success:
  - curl https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f cover.out -F cover -X fix
  - ./codecov -f crosscover.out -F crosscover -X fix

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: f6yNYYYyybz2iZn4QIIvQ9xJiKWEbOk9vJaobxUACouj01u2Ug9jJ0m/6lLPqRqKHg2qYpF67ffVfmFIbDNvRVQxUJHNGX85qwKqZaVHdzGtZgbvp2V+0XTIFS5PgZ8CvTRHIaawxRI8VPYIKxQNC8ytGrjId2tiwHyvk7RpW3B8uIpMmGc4SKetWQfaLIPwAUdS096y+ASiTZeeJA5eqryewz6FgHBO5tX5nz/zlGnz7cpzn71F5JLGTMEuQmv6+oUQuq6M5BTV0bO8sKDObDY1c6CVYk7cXQtd5bFk483o82Yu9fleH8ClT2YaltaCxQOfw59vyDQND8I+kAgOq05g8+WytKZnDrrqB/lsFk0SLW5C9jtu2NBV5T7EWG/9vpU6W3jZxJthrhd1KxUt03ymyg62puvmYTpttvuQVDQt8y2lCMRZj9WW5SicclKXEWbzUuhPLyJWI5mztws7hGp2qnj9IAye9GelbzT4INCWto7m1g2wETT3AYjKcdqFa0h7t/u+jJ6eq3RjxeFLmzFPIgyDbzwyE2GN77gzezVDkTxfeeSv63d2AziSXNs4dJaxQXf2oL04rCxckP8VTyX8O1iOdWF6A9OXwWsBjCZJJiJ1PBHEL7nnkVnpycRE6of6sSbX4vNtQv7eclqHHuUUYnlPXPeYA7Lh1XIJE1A=
