# tools
required = [
  "github.com/quasilyte/go-consistent",
  "golang.org/x/tools/cmd/goimports",
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/percona/pmm"
  branch = "revert-522-revert-516-PMM-5777-inventory-add-external-exporter"

# https://jira.percona.com/browse/PMM-4081
# https://jira.percona.com/browse/PMM-4042
[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  branch = "v2.2.6-percona"
  source = "https://github.com/Percona-Lab/kingpin.git"
